# Generated by Django 5.0.3 on 2024-09-07 00:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_hospitalar', '0003_alter_consulta_medico_alter_consulta_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.CharField(default='ativa', max_length=10),
        ),
        migrations.AddField(
            model_name='medico',
            name='status',
            field=models.CharField(default='ativo', max_length=10),
        ),
        migrations.AddField(
            model_name='paciente',
            name='status',
            field=models.CharField(default='ativo', max_length=10),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='ultimo_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
